/* This file was automatically generated by CasADi 3.6.3.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) UAVModel_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[25] = {21, 1, 0, 21, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20};

/* UAVModel_expl_vde_adj:(i0[17],i1[17],i2[4],i3[21])->(o0[21]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a3, a4, a5, a6, a7, a8, a9;
  a0=0.;
  if (res[0]!=0) res[0][0]=a0;
  if (res[0]!=0) res[0][1]=a0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[3]? arg[3][0] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a0=(a0*a1);
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[3]? arg[3][1] : 0;
  a1=arg[1]? arg[1][1] : 0;
  a0=(a0*a1);
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[3]? arg[3][2] : 0;
  a1=arg[1]? arg[1][2] : 0;
  a0=(a0*a1);
  if (res[0]!=0) res[0][5]=a0;
  a0=1.2000000000000000e-02;
  a1=arg[0]? arg[0][8] : 0;
  a2=(a0*a1);
  a3=1.4285714285714286e+02;
  a4=arg[3]? arg[3][11] : 0;
  a5=arg[1]? arg[1][11] : 0;
  a4=(a4*a5);
  a4=(a3*a4);
  a5=(a2*a4);
  a6=7.0000000000000001e-03;
  a7=arg[0]? arg[0][7] : 0;
  a8=(a6*a7);
  a9=8.3333333333333329e+01;
  a10=arg[3]? arg[3][12] : 0;
  a11=arg[1]? arg[1][12] : 0;
  a10=(a10*a11);
  a9=(a9*a10);
  a10=(a8*a9);
  a5=(a5-a10);
  a10=(a7*a9);
  a11=(a1*a4);
  a10=(a10-a11);
  a10=(a6*a10);
  a5=(a5+a10);
  a10=arg[0]? arg[0][11] : 0;
  a11=5.0000000000000000e-01;
  a12=arg[3]? arg[3][9] : 0;
  a13=arg[1]? arg[1][9] : 0;
  a12=(a12*a13);
  a12=(a11*a12);
  a13=(a10*a12);
  a5=(a5-a13);
  a13=arg[0]? arg[0][12] : 0;
  a14=arg[3]? arg[3][8] : 0;
  a15=arg[1]? arg[1][8] : 0;
  a14=(a14*a15);
  a14=(a11*a14);
  a15=(a13*a14);
  a5=(a5+a15);
  a15=arg[0]? arg[0][9] : 0;
  a16=arg[3]? arg[3][7] : 0;
  a17=arg[1]? arg[1][7] : 0;
  a16=(a16*a17);
  a16=(a11*a16);
  a17=(a15*a16);
  a5=(a5+a17);
  a17=arg[0]? arg[0][10] : 0;
  a18=arg[3]? arg[3][6] : 0;
  a19=arg[1]? arg[1][6] : 0;
  a18=(a18*a19);
  a11=(a11*a18);
  a18=(a17*a11);
  a5=(a5-a18);
  if (res[0]!=0) res[0][6]=a5;
  a5=arg[0]? arg[0][6] : 0;
  a18=(a6*a5);
  a19=(a18*a9);
  a20=arg[3]? arg[3][10] : 0;
  a21=arg[1]? arg[1][10] : 0;
  a20=(a20*a21);
  a3=(a3*a20);
  a20=(a1*a3);
  a21=(a5*a9);
  a20=(a20-a21);
  a6=(a6*a20);
  a19=(a19+a6);
  a2=(a2*a3);
  a19=(a19-a2);
  a2=(a17*a12);
  a19=(a19+a2);
  a2=(a15*a14);
  a19=(a19+a2);
  a2=(a13*a16);
  a19=(a19-a2);
  a2=(a10*a11);
  a19=(a19-a2);
  if (res[0]!=0) res[0][7]=a19;
  a8=(a8*a3);
  a18=(a18*a4);
  a8=(a8-a18);
  a18=(a5*a4);
  a19=(a7*a3);
  a18=(a18-a19);
  a0=(a0*a18);
  a8=(a8+a0);
  a0=(a15*a12);
  a8=(a8+a0);
  a0=(a17*a14);
  a8=(a8-a0);
  a0=(a10*a16);
  a8=(a8+a0);
  a0=(a13*a11);
  a8=(a8-a0);
  if (res[0]!=0) res[0][8]=a8;
  a8=(a1*a12);
  a0=(a7*a14);
  a8=(a8+a0);
  a0=(a5*a16);
  a8=(a8+a0);
  a0=2.;
  a18=1.3966480446927374e+00;
  a19=arg[0]? arg[0][13] : 0;
  a2=arg[0]? arg[0][14] : 0;
  a19=(a19+a2);
  a2=arg[0]? arg[0][15] : 0;
  a19=(a19+a2);
  a2=arg[0]? arg[0][16] : 0;
  a19=(a19+a2);
  a2=arg[3]? arg[3][4] : 0;
  a6=arg[1]? arg[1][4] : 0;
  a2=(a2*a6);
  a6=(a19*a2);
  a6=(a18*a6);
  a6=(a0*a6);
  a20=(a17*a6);
  a8=(a8-a20);
  a20=arg[3]? arg[3][3] : 0;
  a21=arg[1]? arg[1][3] : 0;
  a20=(a20*a21);
  a21=(a19*a20);
  a21=(a18*a21);
  a21=(a0*a21);
  a22=(a10*a21);
  a8=(a8+a22);
  if (res[0]!=0) res[0][9]=a8;
  a8=(a7*a12);
  a22=(a1*a14);
  a8=(a8-a22);
  a22=(a5*a11);
  a8=(a8-a22);
  a22=(a17+a17);
  a23=arg[3]? arg[3][5] : 0;
  a24=arg[1]? arg[1][5] : 0;
  a23=(a23*a24);
  a19=(a19*a23);
  a19=(a18*a19);
  a19=(a0*a19);
  a22=(a22*a19);
  a8=(a8-a22);
  a22=(a15*a6);
  a8=(a8-a22);
  a22=(a13*a21);
  a8=(a8+a22);
  if (res[0]!=0) res[0][10]=a8;
  a8=(a1*a16);
  a12=(a5*a12);
  a8=(a8-a12);
  a12=(a7*a11);
  a8=(a8-a12);
  a12=(a10+a10);
  a12=(a12*a19);
  a8=(a8-a12);
  a12=(a13*a6);
  a8=(a8+a12);
  a12=(a15*a21);
  a8=(a8+a12);
  if (res[0]!=0) res[0][11]=a8;
  a5=(a5*a14);
  a7=(a7*a16);
  a5=(a5-a7);
  a1=(a1*a11);
  a5=(a5-a1);
  a6=(a10*a6);
  a5=(a5+a6);
  a21=(a17*a21);
  a5=(a5+a21);
  if (res[0]!=0) res[0][12]=a5;
  a5=1.6000000000000000e-02;
  a21=(a5*a9);
  a6=40.;
  a1=arg[3]? arg[3][13] : 0;
  a11=arg[1]? arg[1][13] : 0;
  a1=(a1*a11);
  a1=(a6*a1);
  a21=(a21-a1);
  a11=-1.7000000000000001e-01;
  a7=(a11*a4);
  a21=(a21+a7);
  a7=1.;
  a16=casadi_sq(a17);
  a14=casadi_sq(a10);
  a16=(a16+a14);
  a16=(a0*a16);
  a7=(a7-a16);
  a7=(a18*a7);
  a7=(a7*a23);
  a23=(a10*a13);
  a16=(a15*a17);
  a23=(a23-a16);
  a23=(a0*a23);
  a23=(a18*a23);
  a23=(a23*a2);
  a7=(a7+a23);
  a17=(a17*a13);
  a15=(a15*a10);
  a17=(a17+a15);
  a0=(a0*a17);
  a18=(a18*a0);
  a18=(a18*a20);
  a7=(a7+a18);
  a21=(a21+a7);
  if (res[0]!=0) res[0][13]=a21;
  a21=-1.6000000000000000e-02;
  a18=(a21*a9);
  a20=arg[3]? arg[3][14] : 0;
  a0=arg[1]? arg[1][14] : 0;
  a20=(a20*a0);
  a20=(a6*a20);
  a18=(a18-a20);
  a0=1.7000000000000001e-01;
  a17=(a0*a3);
  a18=(a18+a17);
  a18=(a18+a7);
  if (res[0]!=0) res[0][14]=a18;
  a5=(a5*a9);
  a18=arg[3]? arg[3][15] : 0;
  a17=arg[1]? arg[1][15] : 0;
  a18=(a18*a17);
  a18=(a6*a18);
  a5=(a5-a18);
  a0=(a0*a4);
  a5=(a5+a0);
  a5=(a5+a7);
  if (res[0]!=0) res[0][15]=a5;
  a21=(a21*a9);
  a9=arg[3]? arg[3][16] : 0;
  a5=arg[1]? arg[1][16] : 0;
  a9=(a9*a5);
  a6=(a6*a9);
  a21=(a21-a6);
  a11=(a11*a3);
  a21=(a21+a11);
  a21=(a21+a7);
  if (res[0]!=0) res[0][16]=a21;
  a21=arg[3]? arg[3][17] : 0;
  a21=(a21*a1);
  if (res[0]!=0) res[0][17]=a21;
  a21=arg[3]? arg[3][18] : 0;
  a21=(a21*a20);
  if (res[0]!=0) res[0][18]=a21;
  a21=arg[3]? arg[3][19] : 0;
  a21=(a21*a18);
  if (res[0]!=0) res[0][19]=a21;
  a21=arg[3]? arg[3][20] : 0;
  a21=(a21*a6);
  if (res[0]!=0) res[0][20]=a21;
  return 0;
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UAVModel_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void UAVModel_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void UAVModel_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void UAVModel_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int UAVModel_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int UAVModel_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real UAVModel_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UAVModel_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* UAVModel_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UAVModel_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* UAVModel_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int UAVModel_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
